### ISSUE TITLE
Wrong error message in case of errors during reading PassData

### ISSUE THREAD

**Issue by MrZeRo2000** [MrZeRo2000/violetnote-core#6]
bufferedInputStream.reset();
causes "Stream closed" but there should be more meaningful message
Full exception stack trace:
`java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
	at java.base/java.io.BufferedInputStream.reset(BufferedInputStream.java:452)
	at com.romanpulov.violetnotecore.Service.PassData2ReaderServiceV2.fromBufferedStream(PassData2ReaderServiceV2.java:32)
	at com.romanpulov.violetnotecore.Service.PassData2ReaderServiceV2.fromStream(PassData2ReaderServiceV2.java:22)
	at com.romanpulov.violetnotewss.services.PassData2ManagementService.readPassDataFromStream(PassData2ManagementService.java:18)
	at com.romanpulov.violetnotewss.services.PassData2ManagementService.readPassDataFromStream(PassData2ManagementService.java:13)
	at com.romanpulov.violetnotewss.services.AbstractPassDataManagementService.readPassDataFromFile(AbstractPassDataManagementService.java:24)
	at com.romanpulov.violetnotewss.services.AbstractPassDataManagementService.readPassData(AbstractPassDataManagementService.java:60)
	at com.romanpulov.violetnotewss.controller.PassData2ControllerV2.getPassData2(PassData2ControllerV2.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
`

**Comment by MrZeRo2000** [comment]
Done version 2.0.7
